# Generated by Django 5.0.2 on 2024-03-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='flagged_for_cyberbullying',
            field=models.BooleanField(default=False),
        ),
    ]
