# Generated by Django 5.0.2 on 2024-04-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_comment_flagged_for_cyberbullying'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account',
            field=models.BooleanField(default=False),
        ),
    ]
